---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eve-boilerplate/public_html
    - composer install
    # - pnpm --dir ./wp-content/themes/eve-boilerplate install
    # - pnpm --dir ./wp-content/themes/eve-boilerplate build
    # - yarn --cwd ./wp-content/themes/eve-boilerplate install
    # - yarn --cwd ./wp-content/themes/eve-boilerplate build
    - mkdir -p ${DEPLOYPATH}/vendor/
    - rsync -av ./vendor/ ${DEPLOYPATH}/vendor/ --delete
    - mkdir -p ${DEPLOYPATH}/wp-content/mu-plugins/
    - rsync -av ./wp-content/mu-plugins/ ${DEPLOYPATH}/wp-content/mu-plugins/ --delete
    - rsync -av ./wp-content/plugins/ ${DEPLOYPATH}/wp-content/plugins/ --delete
    - rsync -av ./wp-content/themes/ ${DEPLOYPATH}/wp-content/themes/ --delete --exclude=node_modules
